/* 
 * Prepaidforge API
 *
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrepaidforgeSDK.Api;
using PrepaidforgeSDK.Model;
using PrepaidforgeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrepaidforgeSDK.Test
{
    /// <summary>
    ///  Class for testing ApiSignInResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiSignInResponseTests
    {
        // TODO uncomment below to declare an instance variable for ApiSignInResponse
        //private ApiSignInResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiSignInResponse
            //instance = new ApiSignInResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiSignInResponse
        /// </summary>
        [Test]
        public void ApiSignInResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ApiSignInResponse
            //Assert.IsInstanceOf(typeof(ApiSignInResponse), instance);
        }


        /// <summary>
        /// Test the property 'ApiToken'
        /// </summary>
        [Test]
        public void ApiTokenTest()
        {
            // TODO unit test for the property 'ApiToken'
        }
        /// <summary>
        /// Test the property 'TokenValidUntil'
        /// </summary>
        [Test]
        public void TokenValidUntilTest()
        {
            // TODO unit test for the property 'TokenValidUntil'
        }

    }

}
