/* 
 * Prepaidforge API
 *
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrepaidforgeSDK.Api;
using PrepaidforgeSDK.Model;
using PrepaidforgeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrepaidforgeSDK.Test
{
    /// <summary>
    ///  Class for testing CodeDeliveryPojo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CodeDeliveryPojoTests
    {
        // TODO uncomment below to declare an instance variable for CodeDeliveryPojo
        //private CodeDeliveryPojo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CodeDeliveryPojo
            //instance = new CodeDeliveryPojo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CodeDeliveryPojo
        /// </summary>
        [Test]
        public void CodeDeliveryPojoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CodeDeliveryPojo
            //Assert.IsInstanceOf(typeof(CodeDeliveryPojo), instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Serial'
        /// </summary>
        [Test]
        public void SerialTest()
        {
            // TODO unit test for the property 'Serial'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'CodeType'
        /// </summary>
        [Test]
        public void CodeTypeTest()
        {
            // TODO unit test for the property 'CodeType'
        }

    }

}
