/* 
 * Prepaidforge API
 *
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrepaidforgeSDK.Api;
using PrepaidforgeSDK.Model;
using PrepaidforgeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrepaidforgeSDK.Test
{
    /// <summary>
    ///  Class for testing MerchantSignInRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MerchantSignInRequestTests
    {
        // TODO uncomment below to declare an instance variable for MerchantSignInRequest
        //private MerchantSignInRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MerchantSignInRequest
            //instance = new MerchantSignInRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MerchantSignInRequest
        /// </summary>
        [Test]
        public void MerchantSignInRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MerchantSignInRequest
            //Assert.IsInstanceOf(typeof(MerchantSignInRequest), instance);
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

    }

}
