/* 
 * Prepaidforge API
 *
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrepaidforgeSDK.Api;
using PrepaidforgeSDK.Model;
using PrepaidforgeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrepaidforgeSDK.Test
{
    /// <summary>
    ///  Class for testing Money
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MoneyTests
    {
        // TODO uncomment below to declare an instance variable for Money
        //private Money instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Money
            //instance = new Money();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Money
        /// </summary>
        [Test]
        public void MoneyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Money
            //Assert.IsInstanceOf(typeof(Money), instance);
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'FormattedString'
        /// </summary>
        [Test]
        public void FormattedStringTest()
        {
            // TODO unit test for the property 'FormattedString'
        }
        /// <summary>
        /// Test the property 'Csvamount'
        /// </summary>
        [Test]
        public void CsvamountTest()
        {
            // TODO unit test for the property 'Csvamount'
        }
        /// <summary>
        /// Test the property 'RoundedFormattedString'
        /// </summary>
        [Test]
        public void RoundedFormattedStringTest()
        {
            // TODO unit test for the property 'RoundedFormattedString'
        }

    }

}
