/* 
 * Prepaidforge API
 *
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrepaidforgeSDK.Api;
using PrepaidforgeSDK.Model;
using PrepaidforgeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrepaidforgeSDK.Test
{
    /// <summary>
    ///  Class for testing SimpleStockPojo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SimpleStockPojoTests
    {
        // TODO uncomment below to declare an instance variable for SimpleStockPojo
        //private SimpleStockPojo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SimpleStockPojo
            //instance = new SimpleStockPojo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SimpleStockPojo
        /// </summary>
        [Test]
        public void SimpleStockPojoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SimpleStockPojo
            //Assert.IsInstanceOf(typeof(SimpleStockPojo), instance);
        }


        /// <summary>
        /// Test the property 'Product'
        /// </summary>
        [Test]
        public void ProductTest()
        {
            // TODO unit test for the property 'Product'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'PurchasePrice'
        /// </summary>
        [Test]
        public void PurchasePriceTest()
        {
            // TODO unit test for the property 'PurchasePrice'
        }

    }

}
