/* 
 * Prepaidforge API
 *
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrepaidforgeSDK.Api;
using PrepaidforgeSDK.Model;
using PrepaidforgeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrepaidforgeSDK.Test
{
    /// <summary>
    ///  Class for testing SkuRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SkuRequestTests
    {
        // TODO uncomment below to declare an instance variable for SkuRequest
        //private SkuRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SkuRequest
            //instance = new SkuRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SkuRequest
        /// </summary>
        [Test]
        public void SkuRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SkuRequest
            //Assert.IsInstanceOf(typeof(SkuRequest), instance);
        }


        /// <summary>
        /// Test the property 'StockId'
        /// </summary>
        [Test]
        public void StockIdTest()
        {
            // TODO unit test for the property 'StockId'
        }
        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Test]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'CodeType'
        /// </summary>
        [Test]
        public void CodeTypeTest()
        {
            // TODO unit test for the property 'CodeType'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'CustomOrderReference'
        /// </summary>
        [Test]
        public void CustomOrderReferenceTest()
        {
            // TODO unit test for the property 'CustomOrderReference'
        }
        /// <summary>
        /// Test the property 'QuantityHandled'
        /// </summary>
        [Test]
        public void QuantityHandledTest()
        {
            // TODO unit test for the property 'QuantityHandled'
        }
        /// <summary>
        /// Test the property 'RequestHandled'
        /// </summary>
        [Test]
        public void RequestHandledTest()
        {
            // TODO unit test for the property 'RequestHandled'
        }
        /// <summary>
        /// Test the property 'QuantityNeeded'
        /// </summary>
        [Test]
        public void QuantityNeededTest()
        {
            // TODO unit test for the property 'QuantityNeeded'
        }

    }

}
