/* 
 * Prepaidforge API
 *
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrepaidforgeSDK.Api;
using PrepaidforgeSDK.Model;
using PrepaidforgeSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrepaidforgeSDK.Test
{
    /// <summary>
    ///  Class for testing StockRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StockRequestTests
    {
        // TODO uncomment below to declare an instance variable for StockRequest
        //private StockRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StockRequest
            //instance = new StockRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StockRequest
        /// </summary>
        [Test]
        public void StockRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" StockRequest
            //Assert.IsInstanceOf(typeof(StockRequest), instance);
        }


        /// <summary>
        /// Test the property 'Types'
        /// </summary>
        [Test]
        public void TypesTest()
        {
            // TODO unit test for the property 'Types'
        }
        /// <summary>
        /// Test the property 'Skus'
        /// </summary>
        [Test]
        public void SkusTest()
        {
            // TODO unit test for the property 'Skus'
        }
        /// <summary>
        /// Test the property 'MerchantName'
        /// </summary>
        [Test]
        public void MerchantNameTest()
        {
            // TODO unit test for the property 'MerchantName'
        }

    }

}
