/* 
 * Prepaidforge API
 *
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using PrepaidforgeSDK.Client;
using PrepaidforgeSDK.Model;

namespace PrepaidforgeSDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOrdersCodesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// creates order
        /// </remarks>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>CodeDeliveryPojo</returns>
        CodeDeliveryPojo CreateSingleOrder (SkuRequest skuRequest = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// creates order
        /// </remarks>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>ApiResponse of CodeDeliveryPojo</returns>
        ApiResponse<CodeDeliveryPojo> CreateSingleOrderWithHttpInfo (SkuRequest skuRequest = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve code using custom order reference
        /// </remarks>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>CodeDeliveryPojo</returns>
        CodeDeliveryPojo GetResponseOfSingleCodeRequest (SkuRequest skuRequest = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve code using custom order reference
        /// </remarks>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>ApiResponse of CodeDeliveryPojo</returns>
        ApiResponse<CodeDeliveryPojo> GetResponseOfSingleCodeRequestWithHttpInfo (SkuRequest skuRequest = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// creates order
        /// </remarks>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>Task of CodeDeliveryPojo</returns>
        System.Threading.Tasks.Task<CodeDeliveryPojo> CreateSingleOrderAsync (SkuRequest skuRequest = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// creates order
        /// </remarks>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>Task of ApiResponse (CodeDeliveryPojo)</returns>
        System.Threading.Tasks.Task<ApiResponse<CodeDeliveryPojo>> CreateSingleOrderAsyncWithHttpInfo (SkuRequest skuRequest = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve code using custom order reference
        /// </remarks>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>Task of CodeDeliveryPojo</returns>
        System.Threading.Tasks.Task<CodeDeliveryPojo> GetResponseOfSingleCodeRequestAsync (SkuRequest skuRequest = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve code using custom order reference
        /// </remarks>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>Task of ApiResponse (CodeDeliveryPojo)</returns>
        System.Threading.Tasks.Task<ApiResponse<CodeDeliveryPojo>> GetResponseOfSingleCodeRequestAsyncWithHttpInfo (SkuRequest skuRequest = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class OrdersCodesApi : IOrdersCodesApi
    {
        private PrepaidforgeSDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="OrdersCodesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OrdersCodesApi(String basePath)
        {
            this.Configuration = new PrepaidforgeSDK.Client.Configuration { BasePath = basePath };

            ExceptionFactory = PrepaidforgeSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrdersCodesApi"/> class
        /// </summary>
        /// <returns></returns>
        public OrdersCodesApi()
        {
            this.Configuration = PrepaidforgeSDK.Client.Configuration.Default;

            ExceptionFactory = PrepaidforgeSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrdersCodesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public OrdersCodesApi(PrepaidforgeSDK.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = PrepaidforgeSDK.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = PrepaidforgeSDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public PrepaidforgeSDK.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public PrepaidforgeSDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  creates order
        /// </summary>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>CodeDeliveryPojo</returns>
        public CodeDeliveryPojo CreateSingleOrder (SkuRequest skuRequest = null)
        {
             ApiResponse<CodeDeliveryPojo> localVarResponse = CreateSingleOrderWithHttpInfo(skuRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  creates order
        /// </summary>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>ApiResponse of CodeDeliveryPojo</returns>
        public ApiResponse< CodeDeliveryPojo > CreateSingleOrderWithHttpInfo (SkuRequest skuRequest = null)
        {

            var localVarPath = "/1.0/createOrder";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (skuRequest != null && skuRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(skuRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = skuRequest; // byte array
            }

            // authentication (PrepaidforgeAPIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-PrepaidForge-Api-Token")))
            {
                localVarHeaderParams["X-PrepaidForge-Api-Token"] = this.Configuration.GetApiKeyWithPrefix("X-PrepaidForge-Api-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateSingleOrder", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CodeDeliveryPojo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CodeDeliveryPojo) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CodeDeliveryPojo)));
        }

        /// <summary>
        ///  creates order
        /// </summary>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>Task of CodeDeliveryPojo</returns>
        public async System.Threading.Tasks.Task<CodeDeliveryPojo> CreateSingleOrderAsync (SkuRequest skuRequest = null)
        {
             ApiResponse<CodeDeliveryPojo> localVarResponse = await CreateSingleOrderAsyncWithHttpInfo(skuRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  creates order
        /// </summary>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>Task of ApiResponse (CodeDeliveryPojo)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CodeDeliveryPojo>> CreateSingleOrderAsyncWithHttpInfo (SkuRequest skuRequest = null)
        {

            var localVarPath = "/1.0/createOrder";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (skuRequest != null && skuRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(skuRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = skuRequest; // byte array
            }

            // authentication (PrepaidforgeAPIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-PrepaidForge-Api-Token")))
            {
                localVarHeaderParams["X-PrepaidForge-Api-Token"] = this.Configuration.GetApiKeyWithPrefix("X-PrepaidForge-Api-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateSingleOrder", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CodeDeliveryPojo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CodeDeliveryPojo) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CodeDeliveryPojo)));
        }

        /// <summary>
        ///  Retrieve code using custom order reference
        /// </summary>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>CodeDeliveryPojo</returns>
        public CodeDeliveryPojo GetResponseOfSingleCodeRequest (SkuRequest skuRequest = null)
        {
             ApiResponse<CodeDeliveryPojo> localVarResponse = GetResponseOfSingleCodeRequestWithHttpInfo(skuRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Retrieve code using custom order reference
        /// </summary>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>ApiResponse of CodeDeliveryPojo</returns>
        public ApiResponse< CodeDeliveryPojo > GetResponseOfSingleCodeRequestWithHttpInfo (SkuRequest skuRequest = null)
        {

            var localVarPath = "/1.0/getResponseOfSingleCodeRequest";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (skuRequest != null && skuRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(skuRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = skuRequest; // byte array
            }

            // authentication (PrepaidforgeAPIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-PrepaidForge-Api-Token")))
            {
                localVarHeaderParams["X-PrepaidForge-Api-Token"] = this.Configuration.GetApiKeyWithPrefix("X-PrepaidForge-Api-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetResponseOfSingleCodeRequest", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CodeDeliveryPojo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CodeDeliveryPojo) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CodeDeliveryPojo)));
        }

        /// <summary>
        ///  Retrieve code using custom order reference
        /// </summary>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>Task of CodeDeliveryPojo</returns>
        public async System.Threading.Tasks.Task<CodeDeliveryPojo> GetResponseOfSingleCodeRequestAsync (SkuRequest skuRequest = null)
        {
             ApiResponse<CodeDeliveryPojo> localVarResponse = await GetResponseOfSingleCodeRequestAsyncWithHttpInfo(skuRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Retrieve code using custom order reference
        /// </summary>
        /// <exception cref="PrepaidforgeSDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skuRequest"> (optional)</param>
        /// <returns>Task of ApiResponse (CodeDeliveryPojo)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CodeDeliveryPojo>> GetResponseOfSingleCodeRequestAsyncWithHttpInfo (SkuRequest skuRequest = null)
        {

            var localVarPath = "/1.0/getResponseOfSingleCodeRequest";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (skuRequest != null && skuRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(skuRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = skuRequest; // byte array
            }

            // authentication (PrepaidforgeAPIToken) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-PrepaidForge-Api-Token")))
            {
                localVarHeaderParams["X-PrepaidForge-Api-Token"] = this.Configuration.GetApiKeyWithPrefix("X-PrepaidForge-Api-Token");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetResponseOfSingleCodeRequest", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CodeDeliveryPojo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CodeDeliveryPojo) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CodeDeliveryPojo)));
        }

    }
}
