/* 
 * Prepaidforge API
 *
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using PrepaidforgeSDK.Client;
using PrepaidforgeSDK.Api;
using PrepaidforgeSDK.Model;

namespace PrepaidforgeSDK.Test
{
    /// <summary>
    ///  Class for testing ProductsStocksApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProductsStocksApiTests
    {
        private ProductsStocksApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProductsStocksApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductsStocksApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' ProductsStocksApi
            //Assert.IsInstanceOf(typeof(ProductsStocksApi), instance);
        }

        
        /// <summary>
        /// Test FindAllProducts
        /// </summary>
        [Test]
        public void FindAllProductsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.FindAllProducts();
            //Assert.IsInstanceOf(typeof(List<Product>), response, "response is List<Product>");
        }
        
        /// <summary>
        /// Test FindAllStocks
        /// </summary>
        [Test]
        public void FindAllStocksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //StockRequest stockRequest = null;
            //var response = instance.FindAllStocks(stockRequest);
            //Assert.IsInstanceOf(typeof(List<SimpleStockPojo>), response, "response is List<SimpleStockPojo>");
        }
        
    }

}
