/* 
 * Prepaidforge API
 *
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using PrepaidforgeSDK.Client;
using PrepaidforgeSDK.Api;
using PrepaidforgeSDK.Model;

namespace PrepaidforgeSDK.Test
{
    /// <summary>
    ///  Class for testing UserApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UserApiTests
    {
        private UserApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            var config = Configuration.Default;
            config.BasePath = "https://devapi.prepaidforge.com/v1";
            instance = new UserApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' UserApi
            Assert.IsInstanceOf(typeof(UserApi), instance);
        }

        
        /// <summary>
        /// Test SignInWithApi
        /// </summary>
        [Test]
        public void SignInWithApiTest()
        {
            MerchantSignInRequest merchantSignInRequest = new MerchantSignInRequest("USERNAME", "PASSWORD");
            var response = instance.SignInWithApi(merchantSignInRequest);
            Assert.IsInstanceOf(typeof(ApiSignInResponse), response, "response is ApiSignInResponse");
            Console.WriteLine(response);
        }
        
    }

}
