/* 
 * Prepaidforge API
 *
 * The public api for prepaidforge
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PrepaidforgeSDK.Client.OpenAPIDateConverter;

namespace PrepaidforgeSDK.Model
{
    /// <summary>
    /// ApiSignInResponse
    /// </summary>
    [DataContract]
    public partial class ApiSignInResponse :  IEquatable<ApiSignInResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiSignInResponse" /> class.
        /// </summary>
        /// <param name="apiToken">apiToken.</param>
        /// <param name="tokenValidUntil">tokenValidUntil.</param>
        public ApiSignInResponse(string apiToken = default(string), string tokenValidUntil = default(string))
        {
            this.ApiToken = apiToken;
            this.TokenValidUntil = tokenValidUntil;
        }
        
        /// <summary>
        /// Gets or Sets ApiToken
        /// </summary>
        [DataMember(Name="apiToken", EmitDefaultValue=false)]
        public string ApiToken { get; set; }

        /// <summary>
        /// Gets or Sets TokenValidUntil
        /// </summary>
        [DataMember(Name="tokenValidUntil", EmitDefaultValue=false)]
        public string TokenValidUntil { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiSignInResponse {\n");
            sb.Append("  ApiToken: ").Append(ApiToken).Append("\n");
            sb.Append("  TokenValidUntil: ").Append(TokenValidUntil).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApiSignInResponse);
        }

        /// <summary>
        /// Returns true if ApiSignInResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiSignInResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiSignInResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ApiToken == input.ApiToken ||
                    (this.ApiToken != null &&
                    this.ApiToken.Equals(input.ApiToken))
                ) && 
                (
                    this.TokenValidUntil == input.TokenValidUntil ||
                    (this.TokenValidUntil != null &&
                    this.TokenValidUntil.Equals(input.TokenValidUntil))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ApiToken != null)
                    hashCode = hashCode * 59 + this.ApiToken.GetHashCode();
                if (this.TokenValidUntil != null)
                    hashCode = hashCode * 59 + this.TokenValidUntil.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
